# Sample NMEA parameter configuration

device: /dev/ttyUSB0
baudrate: 115200

uart1:
  baudrate: 115200           # C94-M8P specific

nmea:
  set: true
  version: 65
  num_sv: 8
  sv_numbering: 1
  compat: true
  consider: true
  limit82: true
  high_prec: false
  filter:
    pos: true
    msk_pos: true
    time: true
    date: true
    gps_only: true
    track: true
  gnssToFilter:
    gps: false
    sbas: true
    qzss: true
    glonass: false
    beidou: true
  main_talker_id: 1
  gsv_talker_id: 1
  bds_talker_id: [0,0]



debug: 1                    # Range 0-4 (0 means no debug statements will print)

frame_id: m8q
rate: 10                     # in Hz
nav_rate: 10                 # [# of measurement cycles], recommended 1 Hz, may
  # be either 5 Hz (Dual constellation) or
# 8 Hz (GPS only)

gnss:
  glonass: true             # Supported by C94-M8P
  beidou: false             # Supported by C94-M8P
  qzss: false               # Supported by C94-M8P

dgnss_mode: 3               # Fixed mode

inf:
  all: true                   # Whether to display all INF messages in console

# Enable u-blox message publishers
publish:
  all: true
  esf: true
  aid:
    hui: false
  nav:
    posecef: false
